format = "v1"

[metadata]
desc = "U-Boot image for Milk-V Meles (Single-rank, 4G RAM), for RevyOS, 20260504"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20260504"

[[distfiles]]
name = "u-boot-with-spl-meles-4g.bin"
size = 779872
urls = [
  "mirror://revyos/extra/images/meles/20260504/u-boot-with-spl-meles-4g.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "9dd409006187c47ed36b7ad4b149578eb353c801a2c6fe35c4f39a2c89906b53"
sha512 = "b54a795c26017a2ffe508b02e1e83201be0bb54b9b0d6b0c55ce3e04e2b18d4c9d6f6f961196a1b0deb445221debfcf82cafe303819b04b027c40d350dd0a180"

[blob]
distfiles = [
  "u-boot-with-spl-meles-4g.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-meles-4g.bin"
