format = "v1"

[metadata]
desc = "U-Boot image for Milk-V Meles (Dual-rank, 16G RAM), for RevyOS, 20260504"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20260504"

[[distfiles]]
name = "u-boot-with-spl-meles-16g.bin"
size = 779872
urls = [
  "mirror://revyos/extra/images/meles/20260504/u-boot-with-spl-meles-16g.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "b7284979fdb5553cbf75a096d5120ec03c3d4cb28e2ab8de1a01322084cb2cd4"
sha512 = "4d082ede9412bc3a088b09ad291ee28f42f639740dac07775109546fe75a76647bc4153eb69f65aff4a8979286f0395d4a8ac98fdc71a622272c5342d19e5715"

[blob]
distfiles = [
  "u-boot-with-spl-meles-16g.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-meles-16g.bin"
